### ISSUE TITLE
The link in README does not work.

### ISSUE THREAD

**Issue by Maiikiru** [JuliaCJ/Buried-Alive#1]
The error message that the website states is: There is no story with ID "e003fc38-49b6-48f8-9829-56454aaf0d33".
![image](https://github.com/JuliaCJ/Buried-Alive/assets/89322078/45fefb9b-ada9-4e03-baa1-6f0a8a40c800)

**Comment by JuliaCJ** [comment]
Thanks for letting me know! The link should work now!
